- name: "MEDIUM | RHEL-07-020110 | AUDIT | File System automounter must be disabled unless required"
  stat:
      path: /etc/auto.master
  register: rhel_07_020110_audit

- name: "MEDIUM | RHEL-07-030321 | AUDIT | The audit system must take appropriate action when there is an error sending audit records to a remote system."
  stat:
      path: /etc/audisp/audisp-remote.conf
  register: rhel_07_030321_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-030321
      - always

- name: "MEDIUM | RHEL-07-021120 | AUDIT | If the cron.allow file exists it must be group owned by root"
  stat:
      path: /etc/cron.allow
  register: rhel_07_021120_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-021120
      - cron
      - always

- name: "MEDIUM | RHEL-07-021110 | AUDIT | If the cron.allow file exists it must be owned by root"
  stat:
      path: /etc/cron.allow
  register: rhel_07_021110_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-021110
      - cron
      - always
   
- name: "MEDIUM | RHEL-07-020100 | AUDIT | USB mass storage must be disabled."
  find: 
      paths: /etc/modprobe.d/
      file_type: file
      recurse: yes
      contains: '^#?install usb-storage /bin/true'
      hidden: true
  register: rhel_07_020100_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-020100
      - usb
      - always

- name: "MEDIUM | RHEL-07-040180 | AUDIT | The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) authentication communications."
  command: grep -i useldapauth /etc/sysconfig/authconfig
  register: rhel_07_040180_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-040180
      - ldap
      - always

- name: "MEDIUM | RHEL-07-040500 | AUDIT | The operating system must, for networked systems, synchronize clocks with a server that is synchronized to one of the redundant United States Naval Observatory (USNO) time servers, a time server designated for the appropriate DoD network (NIPRNet/SIPRNet), and/or the Global Positioning System (GPS)."
  stat:
      path: /etc/ntp.conf
  register: rhel_07_040500_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-040500
      - ntpd
      - always

- name: "MEDIUM | RHEL-07-040230 | AUDIT | The operating system, if using PKI-based authentication, must implement a local cache of revocation data to certificate validation in case of the inability to access revocation information via the network."
  stat:
      path: /var/lib/pki-kra/conf/server.xml
  register: rhel_07_040230_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-040230
      - always
      - pki

- name: "MEDIUM | RHEL-07-040680 | AUDIT | The system must be configured to prevent unrestricted mail relaying."
  stat:
      path: /etc/postfix/main.cf
  register: rhel_07_040680_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-040680
      - always
      - postfix

- name: "MEDIUM | RHEL-07-040720 | AUDIT | If the Trivial File Transfer Protocol (TFTP) server is required, the TFTP daemon must be configured to operate in secure mode"
  stat:
      path: /etc/xinetd.d/tftp
  register: rhel_07_040720_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-040720
      - always
      - tftp

- name: "MEDIUM | RHEL-07-040420 | AUDIT | The SSH private host key files must have mode 0600 or less permissive."
  find:
      paths: /
      recurse: yes
      file_type: file
      patterns: '*ssh_host*key'
      hidden: true
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_040420_audit
  tags:
      - cat2
      - high
      - audit
      - RHEL-07-040420
      - always
      - ssh

- name: "MEDIUM | RHEL-07-040410 | AUDIT | The SSH public host key files must have mode 0644 or less permissive."
  find:
      paths: /
      recurse: yes
      file_type: file
      patterns: '*.pub'
      hidden: true
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_040410_audit
  tags:
      - cat2
      - high
      - audit
      - RHEL-07-040410
      - always
      - ssh

- name: "MEDIUM | RHEL-07-041010 | AUDIT | Wireless network adapters must be disabled."
  command: nmcli radio wifi
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_041010_audit
  tags:
      - cat2
      - high
      - audit
      - RHEL-07-041010
      - always

- name: "MEDIUM | RHEL-07-010060 | AUDIT | The operating system must enable a user session lock until that user re-establishes access using established identification and authentication procedures."
  find:
      paths: /etc/dconf/db/local.d
      contains: "lock-enabled"
      recurse: yes
  changed_when: no
  failed_when: no
  ignore_errors: yes
  register: rhel_07_010060_audit
  tags:
      - cat2
      - high
      - audit
      - gui
      - RHEL-07-010060
      - always

- name: |
    MEDIUM | RHEL-07-030871 | AUDIT | The operating system must generate audit records for all account creations, modifications, disabling, and termination events that affect /etc/group.
    MEDIUM | RHEL-07-030872 | AUDIT | The operating system must generate audit records for all account creations, modifications, disabling, and termination events that affect /etc/gshadow.
    MEDIUM | RHEL-07-030873 | AUDIT | The operating system must generate audit records for all account creations, modifications, disabling, and termination events that affect /etc/shadow.
    MEDIUM | RHEL-07-030874 | AUDIT | The operating system must generate audit records for all account creations, modifications, disabling, and termination events that affect /etc/opasswd.
  stat:
      path: "{{ item }}"
  register: rhel_07_auditd_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  with_items:
      - /etc/audit
      - /etc/audit/rules.d
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-030871
      - RHEL-07-030872
      - RHEL-07-030873
      - RHEL-07-030874
      - auditd
      - always

- name: "MEDIUM | RHEL-07-031010 | AUDIT | The rsyslog daemon must not accept log messages from other servers unless the server is being used for log aggregation."
  stat:
      path: "/etc/rsyslog.conf"
  register: rhel_07_031010_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - rsyslog
      - RHEL-07-031010
      - always

- name: "MEDIUM | RHEL-07-010070 | AUDIT | System must initiate a screensaver after a 15-minute period."
  find:
      paths: /etc/dconf/db/local.d
      recurse: no
      contains: "^#?idle-delay"
  register: rhel_07_010070_audit
  tags:
      - cat2
      - medium
      - audit
      - RHEL-07-010070

- name: "MEDIUM | RHEL-07-020240 | PATCH | The operating system must define default permissions for all authenticated users in such a way that the user can only read and modify their own files."
  stat:
      path: "/etc/login.defs"
  register: rhel_07_020240_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat2
      - medium
      - logindefs
      - RHEL-07-020240
      - always